### PR TITLE
Add QtQuick.Controls for browser-ng

### PR DESCRIPTION
**Pull request by nfsprodriver**
This module is currently missing for browser-ng to get a context menu.

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Pretty sure we had it before at some point. Maybe it got pulled in as a dependency?

**Comment by NeoTheThird** [comment]
@mariogrip please review

**Comment by Flohack74** [comment]
@mariogrip Pleeease review ;)

**Review by mariogrip — CHANGES_REQUESTED** [review]
This should be added to the sdk-libs dep list, that way we can use these in a development env

**Comment by mariogrip** [comment]
We got controls2, https://github.com/ubports/ubuntu-touch-meta/blob/xenial/sdk-libs-armhf#L22 maybe that has a context we can use?

**Comment by dobey** [comment]
UITK depends on this already, so it should already be on the images. Is it somehow not? Or are you wanting controls2 instead? It would be great if browser-ng could avoid using old controls 1.x if possible.

**Comment by Flohack74** [comment]
Can we close this now with morph browser being finished?

**Comment by dobey** [comment]
> Can we close this now with morph browser being finished?

I'm not sure it was needed anyway, as the module should already have been on the image. I'd say it can be declined now though, yes.

**Pull request closed without merging**
