### PR TITLE
Remove U1DB

### PR DESCRIPTION
**Pull request by mariogrip**
This removes U1DB from the sdk meta packages

See https://github.com/ubports/ubuntu-touch/issues/96

### CODE REVIEW

**Comment by dpniel** [comment]
Hmmm i don't think we are in a position to just remove this right now.

Have we officially notified of the deprecation in anyway apart from the linked bug report? My concern is we have advertised it's [api](https://api-docs.ubports.com/sdk/apps/qml/U1db/index.html?highlight=u1db) on api-docs.ubports.com so we should probably first remove that documentation and replace it with a notice of deprecation which will take place in say OTA-5.

I don't know how many of the core-apps depend on u1db but i do know clock-app does so that will need migrating to something else before we can remove this.

**Comment by NeoTheThird** [comment]
Makes sense. Let's keep this PR open and make a proper deprecation announcement (for either OTA-5 or 6) after OTA-4. That should give us enough time to properly migrate all our components and remove all mentions of it in the docs.

**Review by NeoTheThird — CHANGES_REQUESTED** [review]
Merging blocked until proper deprecation notices have been published, u1db has been removed from the docs, and all our components have been migrated to localstorage or settings.

**Comment by Flohack74** [comment]
Question is, how we do deprecation notes. This one is getting really old.

**Comment by dobey** [comment]
I'm going to close this, as there's been no activity for over a year. We need to come up with a migration plan to move core apps to something else where u1db is being used now, ensure nothing in the store is using it and get a click review error implemented for anything being uploaded which does, announce the deprecation and timeline for disallowing uploads, update and remove docs, etc… before we can remove the package.

**Pull request closed without merging**
