### PR TITLE
Add pyotherside to xenial

### LINKED ISSUE #95: Ship PyOtherSide in the base image
Many Click app developers use pyotherside to write Qt apps in python. In the past, they have had to ship their own copy of the library in their Click. It was decided at [our last developer meeting](https://forums.ubports.com/topic/273/june-1-2017-app-developer-os-developer-meeting/2) that this library should be shipped in the base image.

### PR DESCRIPTION
**Pull request by dpniel**
This resolves https://github.com/ubports/ubuntu-touch/issues/95

### CODE REVIEW

**Comment by Flohack74** [comment]
BTW we should sync those 3 files for package configuration. Apparently only armhf is up2date. Maybe after merging this one. And @dpniel as you mentioned, where to get latest pyotherside version, do we need to build this on our own?

**Comment by dpniel** [comment]
@Flohack74 yeah i noticed they aren't all in sync. I can do a new PR once this one has merged for that.

Regarding where pyotherside is coming from I have packaged it up for [xenial](https://github.com/ubports/pyotherside-packaging) using the tar balls from their github [releases](https://github.com/thp/pyotherside/releases) page.

**Comment by Flohack74** [comment]
Ok I understand. So your package is now already latest? =)

**Comment by mariogrip** [comment]
Could you also add this to arm64?

**Comment by dpniel** [comment]
Sure

**Comment by dpniel** [comment]
Done :-)

**Pull request merged**
