### PR TITLE
Removes really old frameworks

### PR DESCRIPTION
**Pull request by bhdouglass**
Do we even need these around anymore?

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Probably a good idea, but do we have data if anyone still uses them? Any way we could get that out of the openstore?

**Comment by bhdouglass** [comment]
@NeoTheThird surprisingly more that I thought: https://open-store.io/stats . Looks like a bunch of webapps mostly, I've attached a list of apps on those frameworks. Some have been forked and updated, but a few we might not be ready to lose yet.

[old-apps.txt](https://github.com/ubports/ubuntu-touch-meta/files/3304451/old-apps.txt)

**Comment by dobey** [comment]
> [old-apps.txt](https://github.com/ubports/ubuntu-touch-meta/files/3304451/old-apps.txt)

This list is extremely short compared to the numbers on the stats page. Are most of those only on vivid then? The ones in this file also seem to only be based on the 14.10 frameworks, and a lot fewer than indicated on stats page. What's up there?

**Comment by bhdouglass** [comment]
The ones listed in the file are the apps on old frameworks that are not webapps.

**Comment by lduboeuf** [comment]
no updates for that issue ?

**Comment by bhdouglass** [comment]
I'm going to close this since it doesn't make sense to drop these old frameworks yet.

**Pull request closed without merging**
