### PR TITLE
Remove whoopsie, apport and gdbserver

### PR DESCRIPTION
**Pull request by mariogrip**

### CODE REVIEW

**Comment by dobey** [comment]
I think we might want to keep gdbserver here. IIRC it's not for apport, but so you can debug apps remotely on the device, from QtCreator.

**Comment by mariogrip** [comment]
That is true, but it would require libc6-dbg and we don't currently have space to hold this. After oxide is removed we will have a good chunk of space left.

**Review by dobey — APPROVED** [review]
LGTM.

**Comment by dobey** [comment]
Actually, maybe we should leave debugging stuff out of the rootfs by default, and solve remote debugging in some other way. It would be better to have more translations, a11y, and such in the image, over something we don't have a proper SDK to support, and which is only useful to people who need to remotely debug apps during development.

**Pull request merged**
