### PR TITLE
Add qqc2 and suru style

### PR DESCRIPTION
**Pull request by dpniel**
This adds QtQuick Controls 2 and our Suru style to the sdk libs.

### CODE REVIEW

**Review by NeoTheThird — APPROVED** [review]
\o/

**Comment by mariogrip** [comment]
Wonder how this will impact our space problem, how big is it?

**Comment by dpniel** [comment]
@mariogrip Hmmm looking at the packages i think it's a little under 4MB all together. How much space do we have left after removing the qt4 bits?

**Comment by mariogrip** [comment]
That's fine :) lest merge this :+1:

**Pull request merged**
